name: generease
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  url_launcher: ^6.2.5
  live_activities: ^1.9.1+1
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  contacts_service: ^0.6.3
  share_plus: ^7.2.2
  flutter_callkit_incoming: ^2.0.4+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
