"""empty message

Revision ID: 0c23cf211156
Revises: 
Create Date: 2024-03-11 13:37:41.048139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c23cf211156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('birth', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('user_img', sa.BLOB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('requester',
    sa.Column('requester_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('requester_id'),
    sa.UniqueConstraint('requester_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('responser',
    sa.Column('responser_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('best_way', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('responser_id'),
    sa.UniqueConstraint('responser_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('connect',
    sa.Column('connect_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responser_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('connect_way', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['requester.requester_id'], ),
    sa.ForeignKeyConstraint(['responser_id'], ['responser.responser_id'], ),
    sa.PrimaryKeyConstraint('connect_id'),
    sa.UniqueConstraint('connect_id')
    )
    op.create_table('connect_history',
    sa.Column('connect_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connect_id', sa.Integer(), nullable=False),
    sa.Column('responser_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('connect_way', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connect_id'], ['connect.connect_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['requester.requester_id'], ),
    sa.ForeignKeyConstraint(['responser_id'], ['responser.responser_id'], ),
    sa.PrimaryKeyConstraint('connect_history_id'),
    sa.UniqueConstraint('connect_history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connect_history')
    op.drop_table('connect')
    op.drop_table('responser')
    op.drop_table('requester')
    op.drop_table('user')
    # ### end Alembic commands ###
