"""empty message

Revision ID: 82d96b65429f
Revises: 3b91bb98d648
Create Date: 2024-03-25 10:38:07.269576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d96b65429f'
down_revision: Union[str, None] = '3b91bb98d648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responser', sa.Column('best_way', sa.String(length=255), nullable=True))
    op.drop_column('responser', 'best_way_thd')
    op.drop_column('responser', 'best_way_sec')
    op.drop_column('responser', 'best_way_fir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responser', sa.Column('best_way_fir', sa.VARCHAR(length=255), nullable=True))
    op.add_column('responser', sa.Column('best_way_sec', sa.VARCHAR(length=255), nullable=True))
    op.add_column('responser', sa.Column('best_way_thd', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('responser', 'best_way')
    # ### end Alembic commands ###
