"""empty message

Revision ID: 8bbb607c71e3
Revises: bd9cca9cc46c
Create Date: 2024-03-21 17:44:27.467780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbb607c71e3'
down_revision: Union[str, None] = 'bd9cca9cc46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmmd_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmmd_code')
    # ### end Alembic commands ###
