"""empty message

Revision ID: 975859219ef8
Revises: c9f82f5fc60c
Create Date: 2024-03-22 15:09:42.438002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975859219ef8'
down_revision: Union[str, None] = 'c9f82f5fc60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('val', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmmd_code', 'val')
    # ### end Alembic commands ###
