"""empty message

Revision ID: c896dc1d6661
Revises: afc232800eb0
Create Date: 2024-03-22 15:30:29.982107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c896dc1d6661'
down_revision: Union[str, None] = 'afc232800eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('tsk', sa.String(length=400), nullable=True))
    op.drop_column('cmmd_code', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('description', sa.VARCHAR(length=400), nullable=True))
    op.drop_column('cmmd_code', 'tsk')
    # ### end Alembic commands ###
