"""empty message

Revision ID: c9f82f5fc60c
Revises: 8bbb607c71e3
Create Date: 2024-03-22 09:03:25.402717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f82f5fc60c'
down_revision: Union[str, None] = '8bbb607c71e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmmd_cd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmmd_cd',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reserve_culture', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reserve_educate', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reserve_sport', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reserve_medical', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reserve_restaurant', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reserve_etc', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
