"""empty message

Revision ID: 1b0df908e386
Revises: 975859219ef8
Create Date: 2024-03-22 15:10:44.376881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0df908e386'
down_revision: Union[str, None] = '975859219ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('desc', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmmd_code', 'desc')
    # ### end Alembic commands ###
