"""empty message

Revision ID: 4065f1b2fe93
Revises: 82d96b65429f
Create Date: 2024-03-27 15:19:47.760722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4065f1b2fe93'
down_revision: Union[str, None] = '82d96b65429f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responser', sa.Column('active_time', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responser', 'active_time')
    # ### end Alembic commands ###
