"""empty message

Revision ID: 46d674a68a22
Revises: 4065f1b2fe93
Create Date: 2024-04-23 10:59:29.115749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d674a68a22'
down_revision: Union[str, None] = '4065f1b2fe93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noti',
    sa.Column('noti_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connect_id', sa.Integer(), nullable=True),
    sa.Column('noti_title', sa.String(length=255), nullable=True),
    sa.Column('noti_content', sa.String(length=2555), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connect_id'], ['connect.connect_id'], ),
    sa.PrimaryKeyConstraint('noti_id'),
    sa.UniqueConstraint('connect_id'),
    sa.UniqueConstraint('noti_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noti')
    # ### end Alembic commands ###
