"""empty message

Revision ID: afc232800eb0
Revises: 1b0df908e386
Create Date: 2024-03-22 15:26:28.554981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc232800eb0'
down_revision: Union[str, None] = '1b0df908e386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('description', sa.String(length=400), nullable=True))
    op.drop_column('cmmd_code', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmmd_code', sa.Column('desc', sa.VARCHAR(length=400), nullable=True))
    op.drop_column('cmmd_code', 'description')
    # ### end Alembic commands ###
