"""empty message

Revision ID: bd9cca9cc46c
Revises: 0c23cf211156
Create Date: 2024-03-20 11:41:19.296920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9cca9cc46c'
down_revision: Union[str, None] = '0c23cf211156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmmd_cd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserve_culture', sa.String(length=10), nullable=True),
    sa.Column('reserve_educate', sa.String(length=10), nullable=True),
    sa.Column('reserve_sport', sa.String(length=10), nullable=True),
    sa.Column('reserve_medical', sa.String(length=10), nullable=True),
    sa.Column('reserve_restaurant', sa.String(length=10), nullable=True),
    sa.Column('reserve_etc', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmmd_cd')
    # ### end Alembic commands ###
